version: '3.3'

services:
  webserver:
    build: 
      context: ./.docker/Web/Apache2
    depends_on:
      - app
    container_name: web_${APP_NAME:-app}
    restart: always
    ports:
      - '${WEB_HTTP_SERVER_PORT}:80'
    networks:
      - app-net

networks:
  app-net:
    driver: bridge